background {
    monitor =
    blur_passes = 2
    blur_size = 4
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2

    outer_color = rgb(151515)
    inner_color = rgb(200200200)
    font_color = rgb(10, 10, 10)

    fade_on_empty = false
    placeholder_text = Enter Password...
    hide_input = false
    rounding = 10
    position  = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M:%S')"
    font_size = 50
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    font_size = 20
    position = 0, 30
    halign = center
    valign = center
}
