general {
    lock_cmd = hyprlock
    before_sleep_cmd = pidof hyprlock || hyprlock
}

listener {
    timeout = 300
    on-timeout = pidof hyprlock || hyprlock
}

listener {
    timeout = 57600
    on-timeout = systemctl hibernate
}
