general {
    lock_cmd = hyprlock
    before_sleep_cmd = pidof hyprlock || hyprlock
}

listener {
    timeout = 300
    on-timeout = pidof hyprlock || hyprlock
}

# systemd 에 의해(덮개닫힘) suspend 로 진입하게 되면, hypridle 의 타이머가 멈추게 됨.
# hibernate 로 진입하기 위해선, systemd 의 logind.conf와 sleep.conf 설정파일을 사용해야함.
listener {
    timeout = 600
    on-timeout = systemctl suspend
}
