font_family Unifont
font_size 12
modify_font cell_width -50%
window_padding_width 0
background_opacity 1

enabled_layouts splits

tab_bar_style separator
tab_bar_edge top

map ctrl+\ launch --location=hsplit
map ctrl+shift+\ launch --location=vsplit
map alt+h neighboring_window left
map alt+j neighboring_window bottom
map alt+k neighboring_window top
map alt+l neighboring_window right
map alt+shift+h move_window left
map alt+shift+j move_window bottom
map alt+shift+k move_window top
map alt+shift+l move_window right
