enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

[mode.main.binding]
alt-ctrl-shift-s = 'layout v_accordion'
alt-ctrl-shift-w = 'layout h_accordion'
alt-ctrl-shift-e = 'layout tiles'
alt-ctrl-shift-f = 'layout floating'

alt-ctrl-h = "focus left"
alt-ctrl-j = "focus down"
alt-ctrl-k = "focus up"
alt-ctrl-l = "focus right"
alt-shift-h = "move left"
alt-shift-j = "move down"
alt-shift-k = "move up"
alt-shift-l = "move right"

alt-ctrl-space = "layout floating tiling"

alt-ctrl-v = "split vertical"
alt-ctrl-b = "split horizontal"

alt-shift-f = "flatten-workspace-tree"

# 1사분면 (오른쪽 위)으로 floating 윈도우 이동 + 리사이즈
alt-ctrl-w = 'exec-and-forget osascript ~/.config/aerospace/move-window.applescript q1'

# 2사분면 (왼쪽 위)으로 floating 윈도우 이동 + 리사이즈
alt-ctrl-q = 'exec-and-forget osascript ~/.config/aerospace/move-window.applescript q2'

# 3사분면 (왼쪽 아래)으로 floating 윈도우 이동 + 리사이즈
alt-ctrl-a = 'exec-and-forget osascript ~/.config/aerospace/move-window.applescript q3'

# 4사분면 (오른쪽 아래)으로 floating 윈도우 이동 + 리사이즈
alt-ctrl-s = 'exec-and-forget osascript ~/.config/aerospace/move-window.applescript q4'

# 전체 화면 채우기
alt-ctrl-f = 'exec-and-forget osascript ~/.config/aerospace/move-window.applescript full'

# 왼쪽 절반
alt-ctrl-left = 'exec-and-forget osascript ~/.config/aerospace/move-window.applescript left'

# 오른쪽 절반
alt-ctrl-right = 'exec-and-forget osascript ~/.config/aerospace/move-window.applescript right'

# 위쪽 절반
alt-ctrl-up = 'exec-and-forget osascript ~/.config/aerospace/move-window.applescript top'

# 아래쪽 절반
alt-ctrl-down = 'exec-and-forget osascript ~/.config"ctrl", "/ctrl/move-window.applescript bottom'
